### PR TITLE
Bad requests to metrics storage are retried, but should not

### LINKED ISSUE #436: Bad requests to metrics storage are retried, but should not
Mechanism of retries that was introduced in #423 retries requests that return BAD REQUEST status. I've checked that for influxdb implemenetation and that seems strange to me. 
See:
```
      } catch (IOException | UncheckedIOException | RetrofitError | RetryableQueryException e) {
        retries++;
        // TODO: Externalize this as a configurable setting.
        if (retries >= 10)
          throw e;
        log.warn("Retrying metric service query");
      }
```
I think that the better way of retrying retrofit errors is by using custom interceptor where retry policy can be configured more correctly.

### PR DESCRIPTION
**Pull request by Aloren**
Bad requests to metrics storage are retried, but should not 
fixes #436

### CODE REVIEW

File: kayenta-core/src/main/java/com/netflix/kayenta/metrics/SynchronousQueryProcessor.java [hunk 1]
```diff
@@ -96,6 +112,12 @@ public String executeQuery(String metricsAccountName,
     return metricSetListId;
   }
 
+  private boolean isRetryable(RetrofitError e) {
```
Comment (fieldju) [inline kayenta-core/src/main/java/com/netflix/kayenta/metrics/SynchronousQueryProcessor.java]: Am I to understand that the new default logic is to only retry 5xx response, where as the old logic was to retry any non 200-399 responses?

File: kayenta-core/src/main/java/com/netflix/kayenta/metrics/MetricsRetryConfigurationProperties.java [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+
+import lombok.Data;
+import org.springframework.boot.context.properties.ConfigurationProperties;
+import org.springframework.http.HttpStatus;
+
+import java.util.Arrays;
+import java.util.List;
+
+@Data
+@ConfigurationProperties("kayenta.retry")
```
Comment (fieldju) [inline kayenta-core/src/main/java/com/netflix/kayenta/metrics/MetricsRetryConfigurationProperties.java]: Can you add an example of configuring this to https://github.com/spinnaker/kayenta/blob/master/kayenta-web/config/kayenta.yml

File: kayenta-core/src/main/java/com/netflix/kayenta/metrics/SynchronousQueryProcessor.java (hunk 1 above)
Comment (Aloren) [reply kayenta-core/src/main/java/com/netflix/kayenta/metrics/SynchronousQueryProcessor.java]: Yes, you are correct. Should I add other http series into default configuration as well? The intent of this PR was to exclude 4xx response statuses from retries.

Comment (fieldju) [reply kayenta-core/src/main/java/com/netflix/kayenta/metrics/SynchronousQueryProcessor.java]: I don't know if there is a real use case for retrying other responses (0-199, 300+) or not.

**I was just making sure I understand what is changing.**

The situation that comes to my mind that would warrant a retry are 503s (LB issues) and timeouts (network issues)

Comment (fieldju) [reply kayenta-core/src/main/java/com/netflix/kayenta/metrics/SynchronousQueryProcessor.java]: image

What about 409s, I don't think I have actually ever seen that response code in real life, but that seem retry-able.

image

I have seen 429's and they are retry-able usually with some sort of back off policy

File: kayenta-core/src/main/java/com/netflix/kayenta/metrics/MetricsRetryConfigurationProperties.java [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+public class MetricsRetryConfigurationProperties {
+
+    private List<HttpStatus.Series> series = Arrays.asList(HttpStatus.Series.SERVER_ERROR);
```
Comment (fieldju) [inline kayenta-core/src/main/java/com/netflix/kayenta/metrics/MetricsRetryConfigurationProperties.java]: Is it worth adding 408s and 429s to this list and make people opt out of those codes rather than opt in, to maintain backwards compatibility.

Comment (Aloren) [reply kayenta-core/src/main/java/com/netflix/kayenta/metrics/MetricsRetryConfigurationProperties.java]: Ok, I will also add http statuses list that can be retried

File: kayenta-core/src/main/java/com/netflix/kayenta/metrics/SynchronousQueryProcessor.java (hunk 1 above)
Comment (Aloren) [reply kayenta-core/src/main/java/com/netflix/kayenta/metrics/SynchronousQueryProcessor.java]: There is no any backoff in the current retry mechanism, so I'm not sure that it makes sense to retry 429 status by default. 
In any case I've already added both `REQUEST_TIMEOUT` and `TOO_MANY_REQUESTS` to default configuration.

File: kayenta-core/src/main/java/com/netflix/kayenta/metrics/MetricsRetryConfigurationProperties.java (hunk 2 above)
Comment (Aloren) [reply kayenta-core/src/main/java/com/netflix/kayenta/metrics/MetricsRetryConfigurationProperties.java]: yes, of course. I've added default configuration as an example into `kayenta.yml`.
What do you think regarding naming? `kayenta.retry` is ok prefix of better to rename to `kayenta.metrics.retry`?

File: kayenta-core/src/main/java/com/netflix/kayenta/metrics/SynchronousQueryProcessor.java [hunk 4]
```diff
@@ -81,10 +87,20 @@ public String executeQuery(String metricsAccountName,
...
         success = true;
-      } catch (IOException | UncheckedIOException | RetrofitError | RetryableQueryException e) {
+      } catch (RetrofitError e) {
+
+        boolean retryable = isRetryable(e);
+        if (retryable) {
+          retries++;
+          if (retries >= retryConfiguration.getAttempts())
+            throw e;
+          log.warn("Retrying metric service query");
```
Comment (duftler) [inline kayenta-core/src/main/java/com/netflix/kayenta/metrics/SynchronousQueryProcessor.java]: This log message won't give the user much to go on when troubleshooting. Can you include some details that will help when tracing requests?

File: kayenta-core/src/main/java/com/netflix/kayenta/metrics/MetricsRetryConfigurationProperties.java [hunk 5]
```diff
@@ -0,0 +1,28 @@
+package com.netflix.kayenta.metrics;
```
Comment (duftler) [inline kayenta-core/src/main/java/com/netflix/kayenta/metrics/MetricsRetryConfigurationProperties.java]: Please add a copyright header to this file.

File: kayenta-web/config/kayenta.yml [hunk 6]
```diff
@@ -115,6 +115,12 @@ kayenta:
 #    endpoint:
 #      baseUrl: http://remotejudge.example.com/path/to/service
 
+# Retry configuration for metrics fetching from metrics storage (see: MetricsRetryConfigurationProperties)
+  retry:
```
Comment (duftler) [inline kayenta-web/config/kayenta.yml]: Would prefer `kayenta.metrics.retry`, as you mentioned.

**Comment by duftler** [comment]
If this PR does change the set of status codes that are retried, we will need someone from Netflix to verify the behavior against Atlas.
@erikmunson

File: kayenta-core/src/main/java/com/netflix/kayenta/metrics/SynchronousQueryProcessor.java (hunk 4 above)
Comment (Aloren) [reply kayenta-core/src/main/java/com/netflix/kayenta/metrics/SynchronousQueryProcessor.java]: fixed error message for both cases

File: kayenta-core/src/main/java/com/netflix/kayenta/metrics/MetricsRetryConfigurationProperties.java (hunk 5 above)
Comment (Aloren) [reply kayenta-core/src/main/java/com/netflix/kayenta/metrics/MetricsRetryConfigurationProperties.java]: added

File: kayenta-web/config/kayenta.yml (hunk 6 above)
Comment (Aloren) [reply kayenta-web/config/kayenta.yml]: fixed

File: kayenta-core/src/test/groovy/com/netflix/kayenta/metrics/SynchronousQueryProcessorTest.java [hunk 7]
```diff
@@ -0,0 +1,147 @@
+package com.netflix.kayenta.metrics;
```
Comment (duftler) [inline kayenta-core/src/test/groovy/com/netflix/kayenta/metrics/SynchronousQueryProcessorTest.java]: Missing copyright header.

File: kayenta-core/src/main/java/com/netflix/kayenta/metrics/MetricsRetryConfigurationProperties.java (hunk 5 above)
Comment (duftler) [reply kayenta-core/src/main/java/com/netflix/kayenta/metrics/MetricsRetryConfigurationProperties.java]: Thanks. Please use 2019 instead of 2017 and your name or company name instead of Google.

**Comment by Aloren** [comment]
rebased on master
